const MOVIES = ['Westworld','godzilla','Jurassic Park',
'vikings','the simpsons','Breaking bad','Titanic',
'Friends','preacher','star wars',
'harry potter','it','frozen','toy story','deadpool','avengers','fight club',
'alien vs predator','mr robot','the passion of christ',
'tokyo drift','the fast and the furious','resident evil','the thing',
'kill bill','lol','wolverine','flash','a fistful of dollars',
'ronin','prometheus','better call saul','the naked gun','okupas',
'el marginal','parasite','Léon','pulp fiction','rec','a serbian film',
'zombieland','hot fuzz',"the world's end",'shaun of the dead','the wizard of oz',
'citizen kane','casablanca','apocalypse now','The Matrix','Zoolander',
'alien','predator','the lion king','Money heist',"The queen's gambit",
'Stand by me','Amélie','Lost in translation','The terminator','the exorcist',
'Rocky','Oldboy','yellowstone','A Clockwork Orange','Ghostbusters','Memento',
'Return Of The Jedi','Forrest Gump','Reservoir Dogs','Once Upon A Time In The West',
'scary movie','scream','annabelle','the ring','hush','the ritual','28 days later',
'hard boiled','chungking express','mother','garden state','the way home',
'the mandalorian','moon','chernobyl','the room','barbarians','the last kingdom',
'House of wax','mission to mars','mars attacks!','silent hill',
'Kingdom of Heaven','the boys',"It's Always Sunny in Philadelphia",
'the wire','sledge hammer!',
'House','House of cards','lovecraft country','District 9','1917',
'lord of war','full metal jacket','machete','the descent','the last samurai',
'oh,saigon','mortal kombat','the way of the dragon','silicon valley','halt and catch fire',
'the IT crowd','pirates of silicon valley','hackers','the X-Files','the mission',
'highlander II','the shining','the empire strikes back','300'];

export default MOVIES;